### ISSUE TITLE
Asignar las credenciales y headers a los https requests

### ISSUE THREAD

**Issue by joelibaceta** [mercadopago/px-dotnet#17]
Adicionar de forma automática los headers y parametros GET de access_token a las llamadas que lo necesitan en cada request.

https://api.mercadolibre.com/preferences?access_token=ACCESS_TOKEN

Este token debe ser consultado al momento de hacer un request, en caso se defina un atributo user_token a la clase, se debe usar este en lugar del access_token cuando este tenga un valor asignado (Escenario Merchant)

Es decir, si una clase tiene algun valor en su atributo user_token este es el que debe reemplazar al access_token.

De preferencia reducir la dependencia de este requerimiento con la clase de cliente REST.

Estructura de Header de Tracking :

```
{
    "Content-Type": "application/json", 
    "User-Agent": "MercadoPago Java SDK v1.0.1"
} 
```

**Comment by rwillinerktz** [comment]
Joel/Horacio, les dejo una inquietud de como esta resuelto esto en Java, a ver si estamos interpretando algo mal. 
1) Primeramente en getStandardHeaders() de MPBase.java se agrega el content_type:

private static Collection<Header> getStandardHeaders() {
        Collection<Header> colHeaders = new Vector<Header>();
        **colHeaders.add(new BasicHeader(HTTP.CONTENT_TYPE, "application/json"));**
        colHeaders.add(new BasicHeader(HTTP.USER_AGENT, "MercadoPago Java SDK v1.0.1"));
        return colHeaders;
    }

2) Luego, en normalizePayload() de MPRestClient.java, volvemos a introducir este header a los headers que vienen como parámetro:

if (payloadType == PayloadType.JSON) {
      **header = new BasicHeader(HTTP.CONTENT_TYPE, "application/json");**
...
}
else {
 **header = new BasicHeader(HTTP.CONTENT_TYPE, "application/x-www-form-urlencoded");**
}
..
if (header != null) {
   colHeaders.add(header);
}

Le estamos errando en algo de este análisis? Es correcto este proceder?
@joelibaceta  @hdlopez 
cc @gzacharyktz
