### ISSUE TITLE
¿Qué es mejor o más estándar para el trabajo de serialización de objetos a JSON (y viceversa) ?

### ISSUE THREAD

**Issue by hdlopez** [mercadopago/px-dotnet#6]
Entiendo que hace varios años existe la forma de serializar un objeto a JSON utilizando `JSONSerializer`

``` csharp

namespace ExtensionMethods
{
    public static class JSONHelper
    {
        public static string ToJSON(this object obj)
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            return serializer.Serialize(obj);
        }

        public static string ToJSON(this object obj, int recursionDepth)
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            serializer.RecursionLimit = recursionDepth;
            return serializer.Serialize(obj);
        }
    }
}
```

Lo que desconozco (no lo he probado), si es posible usarla para tomar un JSON string y pasarlo a object.

Otra opción y de lo que más he usado, es usar la librería [Newtonsoft.Json](http://www.newtonsoft.com/json/help/html/SerializingJSON.htm). Por lo que he leido esta libería ya viene por default con MVC 4 por ejemplo.

¿Qué opinan? ¿Cuál deberíamos usar? ¿Tenemos alguna otra opción más copada?

**Comment by rwillinerktz** [comment]
Tal como comentás @hdlopez , la librería mas utilizada actualmente y mas "estandarizada" es Newtonsoft.Json (al punto de venir por default en los templates de projecto Visual Studio desde .NET 4.0)
Es la que utilizaríamos nosotros. La conversión a objeto Json, quedaría:

JObject json = JObject.FromObject(resource);

**Comment by hdlopez** [comment]
Excelente @rwillinerktz 👍
